config/routes.rb
Rails.application.routes.draw do

  authenticate :user, lambda { |user| user.admin? } do
    namespace :admin do
      resources :users, only: [:index]

      root to: "users#index"
    end
  end


  root 'homes#index'
  resources :posts do
  resources :comments
  end
  resources :communities do
  resource :subscriptions
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/community.rb
class Community < ApplicationRecord
  mount_uploader :community_image, CommunityImageUploader
  belongs_to :user
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :posts, dependent: :destroy
  has_many :subscriptions
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :post_image, PostImageUploader
  belongs_to :user
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :community
  has_many :comments, dependent: :destroy
  has_rich_text :description
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :community
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts
         has_many :subscriptions
         has_many :communities, through: :subscriptions
        has_many :comments
        has_many :subscribed_posts, through: :communities, source: :posts


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all.order("created_at desc")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :configure_permitted_parameters, if: :devise_controller?

     def configure_permitted_parameters
       added_params = [:name]
       devise_parameter_sanitizer.permit :sign_up, keys: added_params
       devise_parameter_sanitizer.permit :account_update, keys: added_params
     end

     def all_communities
      Community.order(:name)
    end
  
    helper_method :all_communities
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
    before_action :set_post
    def create
       @comment = @post.comments.build(comment_params)
       @comment.user_id = current_user.id
       if  @comment.save
       PostMailer.with(comment: @comment , post: @post).new_response.deliver_now
        respond_to do |format|
        format.js
        end
        else
            format.html {render :new, status: :unprocessable_entity}
       end 
    end

    private

    def set_post
    @post = Post.find(params[:post_id])        
    end
    def comment_params
        params.require(:comment).permit(:reply)
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_user!
    def index
      @communities = Community.all  
    end

    def new
    @community = Community.new
    end
    def create  
    @community = Community.create(community_params)
    
    if @community.save
        redirect_to communities_path	
    else
        render :new
        end
    end
    def show
        @community = Community.friendly.find(params[:id])
        @posts = Post.where(:community_id => @community)
        end    
    def edit
     @community = Community.friendly.find(params[:id])   
    end

    def update
        @community = Community.friendly.find(params[:id])   
    @community.update(community_params)
    redirect_to @community
    end

    def destroy
     @community = Community.friendly.find(params[:id])
     @community.destroy
     redirect_to communities_path   
    end

    private
    def community_params
    params.require(:community).permit(:title, :name, :description,:community_image,:user_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    if user_signed_in? 
    @posts = current_user.subscribed_posts
    else
      @posts = Post.all 
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.create(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :name, :description, :user_id,:post_image,:community_id)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
before_action :set_community
    
    def create
        @subscription = @community.subscriptions.where(user_id: current_user.id).first_or_create
        respond_to do |format|
        format.js
        end
    end

    def destroy
        @subscription = @community.subscriptions.where(user_id: current_user.id).first_or_create
        @subscription.destroy
        respond_to do |format|
        format.js
        end
    end

    private

    def set_community
        @community = Community.friendly.find(params[:community_id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user.username %></p>
  <p><%= user.email %></p>
<% end %>

app/views/comments/_comment.html.erb
<div class="comment-content">
<p><%= comment.reply%></p>
</div>

app/views/comments/_form.html.erb
<div class="comment-box">
<%= form_for([@post, @comment], remote: true) do |f| %>
<%= f.label :reply %>
<%= f.text_area :reply %>
<%= f.submit %>
<% end %>

</div>

app/views/comments/create.js.erb
var comments = document.getElementById("comments")
var commentField = document.getElementById("comment_reply")
comments.insertAdjacentHTML("beforeend", "<%= escape_javascript(render (@comment))%>")
commentField.value = ""

app/views/communities/_form.html.erb
<%= form_with(model: @community, local: true)  do |f| %>
<div class="field">
<%= f.label :title %>
<%= f.text_field :title %>
</div>
<div class="field">
<%= f.label :name %>
<%= f.text_field :name %>
</div>
<div class="field">
<%= f.label :description %>
<%= f.text_area :description %>
</div>
<div class="field">
<%= f.label :community_image %>
<%= f.file_field :community_image %>
<%= f.hidden_field :user_id, value: current_user.id %>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/communities/edit.html.erb
<h1 class="form-heading">Edit Community</h1>
<%= render  "form" %>

app/views/communities/index.html.erb
<h1>All Community</h1>
<div class="container">
<div class="row justify-content-center">
<div class="col-lg-12">
<% @communities.each do |community| %>

<div class="community-area text-center">
<div class="row align-items-center">
<div class="col-lg-4">
<div class="img-area-2">
<%= image_tag community.community_image.thumb.url if community.community_image.present? %>
</div>
</div>
<div class="col-lg-8">
<div class="">
<h2><%= community.user.name %></h2>
<h4><%= community.name%></h4>
<h3><%= community.title%></h3>
<p><%= community.description%></p>
</div>
</div>
</div>
<div class="open-icon">
<i class="fas fa-ellipsis-v"></i>
</div>
<div class="comunity-area-3">
<%= link_to  "Back", communities_path(@community) %>
<%= link_to  "Edit", edit_community_path(community) %>
<%= link_to  "delete", @community, method: :delete, data: {confirm: "are you sure"} %>
</div>
</div>
<% end %>

</div>
</div>
</div>

app/views/communities/new.html.erb
<h1 class="form-heading">New Community</h1>
<%= render  "form" %>

app/views/communities/show.html.erb
<div class="container">
<div class="row justify-content-center">
<div class="col-lg-12">
<div class="community-area text-center">
<div class="row align-items-center">
<div class="col-lg-4">
<div class="img-area-2">
<%= image_tag @community.community_image.thumb.url if @community.community_image.present? %>
</div>
</div>
<div class="col-lg-8">
<div class="">
<h2><%= @community.user.name %></h2>
<h4><%= @community.name%></h4>
<h3><%= @community.title%></h3>
<p><%= @community.description%></p>
</div>
<div id="subscribe-block">
<%= render  "subscriptions/subscription", community: @community %>
</div>
</div>
</div>
<div class="open-icon">
<i class="fas fa-ellipsis-v"></i>
</div>
<div class="comunity-area-3">
<%= link_to  "Back", communities_path %>
<%= link_to  "Edit", edit_community_path %>
<%= link_to  "delete", @community, method: :delete, data: {confirm: "are you sure"} %>
</div>
</div>
</div>
</div>
</div>

<%= render  @posts %>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditApp3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>
  <header class="header">
  <div class="container-fluid">
  <div class="row align-items-center justify-content-between">
  <div class="col-lg-3">
  <%= image_tag("img-1.png", alt: "", class:"img-fluid logo-img") %>
  </div>
  <div class="col-lg-5">
  <div class="all-community">
  <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    All Community
  </button>
   <ul class="dropdown-menu"aria-labelledby="dropdownMenuButton1">
        <% all_communities.each do |community| %> 
          <li><%= link_to community.name, community_path(community) %></li>
        <% end %>
      </ul>
</div>
 </div>
  </div>
  <div class="col-lg-4">
  <div class="header-btn">
  <% if user_signed_in? %>
  <%= link_to  "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-primary btn-a" %>
  <%= link_to 'New Post', new_post_path, class: "btn btn-primary btn-a" %>
  <%= link_to 'New Community', new_community_path, class: "btn btn-primary btn-a" %>
  <% else %>
  <%= link_to  "Sign in", new_user_session_path, class: "btn btn-primary btn-a" %>
  <%= link_to  "Sign Up",new_user_registration_path, class: "btn btn-primary btn-a" %>
  <% end %>
  </div>
  </div>
  </div>
  </div>
  </header>
    <%= yield %>
    <%= javascript_pack_tag 'main', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
<div class="row justify-content-center">
<div class="col-lg-10">
<%= form_with(model: post) do |form| %>
<h1 class="form-heading">New Post</h1>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :community %>
    <%= collection_select(:post, :community_id, Community.all, :id, :name) %>
    
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="field">
    <%= form.label :post_image %>
    <%= form.file_field :post_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>
</div>
</div>

app/views/posts/_post.html.erb
<div class="post-section">
<div class="container">
<div class="row justify-content-center">
<div class="col-lg-6">
<p id="notice"><%= notice %></p>

    <% @posts.each do |post| %>
<div class="post-area">
    <%= post.user.name %>
      <div class="img-area">
          <%= image_tag post.post_image.thumb.url if post.post_image.present? %>
      </div>
      <h2><%= post.title %></h2>
        <h3><%= post.name %></h3>
        <p class="para"><%= post.description %></p>
        <div class="d-flex justify-content-end btn-area">
        <%= link_to 'Show', post, class: "btn-a btn-b btn btn-primary" %>
        <%= link_to 'Edit', edit_post_path(post), class: "btn-a btn-c btn btn-warning" %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-a btn btn-danger" %>
        </div>
</div>
    <% end %>
</div>
</div>
</div>
</div>

app/views/posts/edit.html.erb
    
<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render  @posts %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="post-section">
<div class="container">
<div class="row justify-content-center">
<div class="col-lg-6">

<p id="notice"><%= notice %></p>

<div class="post-area">
    <%= @post.user.name %>
      <div class="img-area">
          <%= image_tag @post.post_image.thumb.url if @post.post_image.present? %>
      </div>
      <h2><%= @post.title %></h2>
        <h3><%= @post.name %></h3>
        <p><%= @post.description %></p>
        <div class="d-flex justify-content-between btn-area">
        <%= link_to 'Show', @post, class: "btn-a  btn btn-primary" %>
        <%= link_to 'Edit', edit_post_path(@post), class: "btn-a btn btn-warning" %>
        <%= link_to 'Back', posts_path, class: "btn-a btn btn-dark" %>
        <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-a btn btn-danger" %>
        </div>
<%= render  "comments/form" %>

<div id="comments">
   <%= render  @comments %>
</div>
</div>


</div>
</div>
</div>
</div>

app/views/subscriptions/_subscribe.js.erb
var subscribeblock = document.getElementById("subscribe-block")
subscribeblock.innerHTML = ""
subscribeblock.insertAdjacentHTML('beforeend', "<%= escape_javascript(render(partial: "subscriptions/subscription", community: @community ))%>")

app/views/subscriptions/_subscription.html.erb
<% if user_signed_in? %>
  <%  unless current_user.communities.include? @community %>
    <%= link_to  "subscribe", community_subscriptions_path(@community), method: :post, remote: true, class: "subscribe-btn"%>
    <% else %>
    <%= link_to  "unsubscribe", community_subscriptions_path(@community), method: :delete, remote: true, class: "subscribe-btn" %>
    
  <% end %>
<% end %>

app/views/subscriptions/create.js.erb
<%= render  "subscribe" %>

app/views/subscriptions/destroy.js.erb
<%= render  "subscribe" %>